== ZEN Oculus display system

=== Clone

Clone https://github.com/zigen-project/zen-oculus-display-system[this repository]
with its submodules as well.

[source,sh]
```
git clone https://github.com/zigen-project/zen-oculus-display-system.git --recursive
```

=== Basic environment setup

This project is an Android project using the OpenXR Mobile SDK provided by
Oculus. Follow the developer documentation for Oculus' OpenXR Mobile SDK to set
up a basic environment.

This will likely include,

* Setting up Oculus Quest/Quest2 in developer mode.
* Development environment for Android projects.
* Download Oculus OpenXR Mobile SDK package

=== Configuration files

Place a file named `local.properties` in the root directories of this project
and set the following items.

* `sdk.dir`  : Path to the Android SDK directory
* `ovr_openxr_mobile_sdk.dir`: Path to the Oculus OpenXR Mobile SDK directory
* `cmake.dir`: (optional) Path to CMake direcory you want to use

[source,property,title="local.properties"]
----
sdk.dir=/path/to/Android/sdk
ovr_openxr_mobile_sdk.dir=/path/to/ovr_openxr_mobile_sdk_42.0
cmake.dir=/path/to/Android/sdk/cmake/3.22.1
----

=== Build & Run

Use Android Studio to build and run, or do as you like.
